config/urls.py
from django.contrib import admin
from django.urls import path, include
from home import base_views

urlpatterns = [
    path('article/', include('article.urls')),
    path('admin/', admin.site.urls),
    path('calender/', include('calender.urls')),
    path('common/', include('common.urls')),
    path('home/', include('home.urls')),
    path('manager/', include('manager.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

home/urls.py
from django.urls import path
from . import base_views

# 앱 마다 명칭 다르게 하기
app_name = 'home'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
]

manager/urls.py
from django.urls import path

from . import manager_views

# 앱 마다 명칭 다르게 하기
app_name = 'manager'

urlpatterns = [
    # article_views.py
    path('list/', manager_views.article_list, name='article_list'),
    path('<int:article_id>/', manager_views.reinforce, name='reinforce'),
]

manager/models.py
from django.db import models

# Create your models here.

windup/models.py
from django.db import models

class Post(models.Model):
    writer = models.CharField(max_length=20)
    title = models.CharField(max_length=200)
    content = models.TextField()
    team = models.TextField()
    date = models.DateTimeField()

manager/views/manager_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.dateformat import DateFormat
from datetime import datetime, timedelta
from article.models import Article

def date_range():
    today = DateFormat(datetime.now()).format('ymd')
    start = datetime.strptime(today, "%y%m%d") - timedelta(days=4)
    dates = [(start + timedelta(days=i)).strftime("20%y-%m-%d") for i in range(5)]
    return dates

def article_list(request):
    """
    article 출력
    """
    print("dsdsds")
    page = request.GET.get('page','1') #GET 방식으로 정보를 받아오는 데이터
    team_text = request.GET.get('team')
    date = request.GET.get('date')
    dates = date_range()
    if(date != None):
        date_conver = date.replace("-","")
    else:
        date_conver = dates[4].replace("-","")

    #dates[4] = 현재 날짜
    if(team_text != '전체' and team_text != None and date != None):
        article = Article.objects.filter(article_team=team_text,written_date=date_conver).order_by('-written_time')
    #팀만 선택할 경우 기본 값으로 오늘로 가게된다.
    elif(team_text == None and date == None):
        article = Article.objects.filter(written_date=date_conver).order_by('-written_time')
    elif(team_text == '전체' and date == None):
        article = Article.objects.filter(written_date=date_conver).order_by('-written_time')
    elif(team_text == '전체' and date != None):
        article = Article.objects.filter(written_date=date_conver).order_by('-written_time')
    else:
        article = Article.objects.filter(article_team=team_text, written_date=date_conver).order_by('-written_time')

    #페이지네이션
    paginator = Paginator(article, '10') #Paginator(분할될 객체, 페이지 당 담길 객체수)
    article_list = paginator.page(page) #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장

    context = {
        'team_text': team_text,
        'article_list': article_list,
        'dates': dates,
     }

    return render(request, 'manager/manager_articleList.html', context)

#강화학습
def reinforce(request,article_id):

    print(article_id)
    article = get_object_or_404(Article, pk=article_id)
    article_texts = article.article_content.split('.')
    context = {
        'article_texts': article_texts,
        'article': article,
     }
    return render(request, 'manager/manager_reinforce.html', context)

templates/manager/manager_articleList.html
<!--상속-->
{% extends 'manager_base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/article.css' %}">
    <div class="header">
        <h1>뉴스</h1>
    </div>

    <form method="get" action="" class="form" >
        <div style="margin-left: 80%; margin-top: 2%;">
        팀 선택
      <select name="team" id="id_team" onchange="location = this.value;">
        <option class="전체" value="?team=전체" >전체</option>
        <option class="삼성" value="?team=삼성">삼성</option>
        <option class="롯데" value="?team=롯데">롯데</option>
        <option class="NC" value="?team=NC">NC</option>
        <option class="KT" value="?team=KT">KT</option>
        <option class="LG" value="?team=LG">LG</option>
        <option class="두산" value="?team=두산">두산</option>
        <option class="키움" value="?team=키움">키움</option>
        <option class="SSG" value="?team=SSG">SSG</option>
        <option class="KIA" value="?team=KIA">KIA</option>
        <option class="한화" value="?team=한화">한화</option>
      </select>
    </div>
    <div class="container">
        {% if article_list %}
        <ul class="list">
            {% for article in article_list %}
            <li class="item">
                <h3><a href="{% url 'manager:reinforce' article.id%}" style="color: black">{{ article.article_title }}</a></h3>
                <div class="info">
                    <div class="written_team"><span>구단 | </span>{{ article.article_team }}</div>
                    <div class="written_time"><span>작성한 날짜 | </span>{{ article.written_date|slice:"4:6"}}월 {{ article.written_date|slice:"6:8"}}일 {{ article.written_time }}</div>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <li>
          <div class="title">기사가 없습니다.</div>
        </li>
        {% endif %}
    </div>
        <!-- 페이징처리 시작 -->
    <div id="paging">
        <ul class="pagination justify-content-center" style="margin-top: 2rem;">
            <!-- 이전페이지 -->
            {% if article_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'manager:article_list' %}?&page={{ article_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in article_list.paginator.page_range %}
            {% if page_number == article_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="{% url 'manager:article_list' %}?&page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="{% url 'manager:article_list' %}?&page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if article_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'manager:article_list' %}?&page={{ article_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <!-- 페이징처리 끝 -->
    <!--  날짜는 했는데 쿼리스트링을 못하겠음-->
    <div>
        <ul class="bottomDateList" style="list-style:none; margin-left: 18%;">
            {% for date in dates %}
            <li class="date" style="display: inline;">
                <a id ="date" href="{% url 'manager:article_list' %}?team={{ team_text }}&date={{ date | urlencode }}" style="color: black">{{ date }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    </form>

<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/article.js' %}"></script>
<script>
var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;
    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
        }
    }
};
</script>

{% endblock %}

templates/manager/manager_reinforce.html
<!--상속-->
{% extends 'manager_base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="/static/css/reinforce.css?we">

<div class="title">
    <h1>{{article.article_title}}</h1>
</div>

<div class="wrapper">

    <span class="prev">《</span>

    <span class="next">》</span>

    <div class="scroll">
        <ul>
            {% for article_text in article_texts %}
            <li class="item">
                <a>{{article_text}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="reinforce">
    <input type="button"  id="pos" onclick="colorChange1()" class="pos" name="{{ article.id }}" value="긍정">
    <input type="button"  id="fence" onclick="colorChange2()" class="fence" name="{{ article.id }}" value="중립">
    <input type="button"  id="neg" onclick="colorChange3()" class="neg" name="{{ article.id }}" value="부정">
</div>

<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<script>
    $(function(){
        var oScroll=$('.scroll>ul'),oLi=oScroll.find('li'),oLen=oLi.length,oPrev=$('.prev'),oNext=$('.next'),oWidth=oLi.eq(0).outerWidth(true),iNow= 1,oCur=$('.count>em'),oCount=$('.count>i'),iTimer=null;
        oScroll.width(oWidth*oLen);
        oCount.html(oLen);
        function count(){
            oCur.html(iNow);
        }

        function Prev(){
            oScroll.css({marginLeft:-oWidth+'px'}).find('li:last').prependTo(oScroll);
            oScroll.stop(true,true).animate({marginLeft:0+'px'},600);
            iNow=iNow>1?iNow-1:oLen;
            count(iNow);
        }

        function Next(){
            oScroll.stop(true,true).animate({marginLeft:-oWidth+'px'},600,function(){
            oScroll.css({marginLeft:0}).find('li:first').appendTo(oScroll);
            })
            iNow=iNow<oLen?iNow+1:1;
            count(iNow);
        }
        oPrev.bind('click',Prev);
        oNext.bind('click',Next);
    })

</script>
<script>
    function colorChange1(){
    var posTag = document.getElementById("pos");
    var fenceTag = document.getElementById("fence");
    var negTag = document.getElementById("neg");
    posTag.style.backgroundColor = "#9E8AEF";
    fenceTag.style.backgroundColor = "#EFEFEF";
    negTag.style.backgroundColor = "#EFEFEF";
    }

    function colorChange2(){
    var posTag = document.getElementById("pos");
    var fenceTag = document.getElementById("fence");
    var negTag = document.getElementById("neg");
    posTag.style.backgroundColor = "#EFEFEF";
    fenceTag.style.backgroundColor = "#9E8AEF";
    negTag.style.backgroundColor = "#EFEFEF";
    }

    function colorChange3(){
    var posTag = document.getElementById("pos");
    var fenceTag = document.getElementById("fence");
    var negTag = document.getElementById("neg");
    posTag.style.backgroundColor = "#EFEFEF";
    fenceTag.style.backgroundColor = "#EFEFEF";
    negTag.style.backgroundColor = "#9E8AEF";
    }
</script>

{% endblock %}