article/urls.py
from django.urls import path

from . import article_views

# 앱 마다 명칭 다르게 하기
app_name = 'article'

urlpatterns = [
    # article_views.py
    path('list/', article_views.article_list, name='article_list'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from home import base_views

urlpatterns = [
    path('article/', include('article.urls')),
    path('admin/', admin.site.urls),
    path('calender/', include('calender.urls')),
    path('common/', include('common.urls')),
    path('home/', include('home.urls')),
    path('manager/', include('manager.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

home/urls.py
from django.urls import path
from . import base_views

# 앱 마다 명칭 다르게 하기
app_name = 'home'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
]

manager/urls.py
from django.urls import path

from . import manager_views

# 앱 마다 명칭 다르게 하기
app_name = 'manager'

urlpatterns = [
    # article_views.py
    path('list/', manager_views.article_list, name='article_list'),
    path('<int:article_id>/', manager_views.reinforce, name='reinforce'),
]

windup/views/base_views.py
from django.shortcuts import render, get_object_or_404


def index(request):
    """
    windup 목록 출력
    """
    return render(request, 'windup/home.html')

templates/base.html
<!-- 모든 템플릿이 상속해야하는 템플릿이다. -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>windUp!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/manager_base.html
<!-- 모든 템플릿이 상속해야하는 템플릿이다. -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>windUp!</title>
</head>
<body>
{% include "manager_navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/manager_navbar.html
<!--네비게이션 바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'home:index' %}">WindUp</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'manager:article_list' %}">강화 학습</a>
            </li>
        </ul>
    </div>
</nav>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'home:index' %}">WindUp</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'home:index' %}">HOME</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" >분위기예측</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link"  href="{% url 'article:article_list' %}">뉴스</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'manager:article_list' %}">관리자</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.userid }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>