config/urls.py
from django.contrib import admin
from django.urls import path, include
from home import base_views

urlpatterns = [
    path('article/', include('article.urls')),
    path('admin/', admin.site.urls),
    path('calender/', include('calender.urls')),
    path('common/', include('common.urls')),
    path('home/', include('home.urls')),
    path('manager/', include('manager.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

home/urls.py
from django.urls import path
from . import base_views

# 앱 마다 명칭 다르게 하기
app_name = 'home'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
]

windup/urls.py
from django.urls import path

from .views import base_views, post_views

# 앱 마다 명칭 다르게 하기
app_name = 'post'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),

    # post_views.py
    path('post/list/',
         post_views.post_list, name='post_list'),
    path('post/create/',
         post_views.post_create, name='post_create'),
    path('<int:post_id>/',
         post_views.post_detail, name='post_detail'),

]

windup/views/post_views.py
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Post
from ..forms import PostForm
from django.contrib import messages

def post_list(request):
    """
    windup 목록 출력
    """
    post_list = Post.objects.order_by('-date')
    context = {'post_list': post_list}
    return render(request, 'windup/post_list.html', context)

def post_create(request):
    """
    windup 게시글등록
    """
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.date = timezone.now()
            post.save()
            return redirect('post:index')
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'windup/post_form.html', context)

def post_detail(request, post_id):
    """
    windup 내용 출력
    """
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'windup/post_detail.html', context)

templates/post/post_detail.html
<!--상속-->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ post.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ post.date }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/post/post_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="writer">작성자</label>
            <input type="text" class="form-control" name="writer" id="writer"
                   value="{{ form.writer.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">등록하기</button>
    </form>
</div>
{% endblock %}

templates/post/post_list.html
<!--상속-->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
            <th>작성자</th>
        </tr>
        </thead>
        <tbody>
        {% if post_list %}
        {% for post in post_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'post:post_detail' post.id %}">{{ post.title }}</a>
            </td>
            <td>{{ post.date }}</td>
            <td>{{ post.writer }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'post:post_create' %}" class="btn btn-primary">게시글 등록하기</a>
</div>
{% endblock %}